### ISSUE TITLE
Could not initialize class ZstdInputStream error

### ISSUE THREAD

**Issue by hegdemahendra** [dustin-johnson/timezonemap#4]
Hi Team,

I have used timezonemap jar in my Flink application to find timezone information by lat-long.

It worked in local machine properly and when deployed to server I got below error -

 

java.lang.NoClassDefFoundError: com/github/luben/zstd/ZstdInputStream

                at us.dustinj.timezonemap.data.DataLocator.getDataInputStream(DataLocator.java:22)

                at us.dustinj.timezonemap.TimeZoneMap.forRegion(TimeZoneMap.java:92)

                at us.dustinj.timezonemap.TimeZoneMap.forEverywhere(TimeZoneMap.java:60)

                at dtap.service.TimezoneService.<init>(TimezoneService.java:17)

                at functions.processors.KernelIntgrationProcessor.processElement(KernelIntgrationProcessor.java:47)

                at functions.processors.KernelIntgrationProcessor.processElement(KernelIntgrationProcessor.java:23)

                at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66)

                at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:202)

                at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.run(OneInputStreamTask.java:105)

                at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)

                at org.apache.flink.runtime.taskmanager.Task.run(Task.java:704)

                at java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.ClassNotFoundException: com.github.luben.zstd.ZstdInputStream

                at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

                at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)

                at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

                ... 12 more

 

 

Then I copied 'zstd-jni-1.3.7-1.jar' jar file to Flink's /lib directory.

It worked initially, but after 2-3 times redeployment it started getting below error -

 

java.lang.NoClassDefFoundError: Could not initialize class com.github.luben.zstd.ZstdInputStream

                at org.apache.commons.compress.compressors.zstandard.ZstdCompressorInputStream.<init>(ZstdCompressorInputStream.java:43)

                at us.dustinj.timezonemap.data.DataLocator.getDataInputStream(DataLocator.java:22)

                at us.dustinj.timezonemap.TimeZoneMap.forRegion(TimeZoneMap.java:92)

                at us.dustinj.timezonemap.TimeZoneMap.forEverywhere(TimeZoneMap.java:60)

                at dtap.service.TimezoneService.<init>(TimezoneService.java:17)

                at functions.processors.KernelIntgrationProcessor.processElement(KernelIntgrationProcessor.java:47)

                at functions.processors.KernelIntgrationProcessor.processElement(KernelIntgrationProcessor.java:23)

                at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66)

                at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:202)

                at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.run(OneInputStreamTask.java:105)

                at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)

                at org.apache.flink.runtime.taskmanager.Task.run(Task.java:704)

                at java.lang.Thread.run(Thread.java:748)

 

 

    Is this jar/class (ZstdInputStream) dependent on any native library/file ? Is there any chance of file curruptin?

 
    Thanks in advance,
    Mahendra

**Comment by dustin-johnson** [comment]
Yes, this library does use a native component for speedy decompression. Were you able to work round this issue?

**Comment by hegdemahendra** [comment]
No I could not find any workaround yet. :(
Is this possible skip/comment native library usage part? Or do you recommend any other workaround ?

**Comment by dustin-johnson** [comment]
Yes, it's possible to skip the decompression entirely by extracting the map database to a file ahead of time. You can then provide the extracted map database during initialization. Here is an example:

```Java
File mapDb = new File("<SOME_PATH>\\mapDb.bin");

// Step 1: Extract the map database and save it to a file. The internal database is uncompressed during 
// extraction (its size is currently ~50MB). Do this on a computer where TimeZoneMap works well.
try (InputStream input = DataLocator.getDataInputStream();
        OutputStream output = new FileOutputStream(mapDb)) {
    IOUtils.copy(input, output);
}

// Step 2: Use the extracted map database in initialization.
try (InputStream input = new FileInputStream(mapDb)) {
    TimeZoneMap map = TimeZoneMap.forRegion(input, -90.0, -180.0, 90.0, 180.0);

    assertThat(map.getOverlappingTimeZone(40.169102, -123.283836).getZoneId())
            .isEqualTo("America/Los_Angeles");
}
```

**Comment by hegdemahendra** [comment]
Ohh this is what I was looking for !
Thanks a lot , it worked fine in my local machine and will try tobuse this in server .

And just wanted to know if I need to keep refreshing/updating this mapdb local file?If so what is the freq? when you release new version of jar or something else ?

Thanks for your suggestions :)

**Comment by dustin-johnson** [comment]
You're right, the map only changes (at most) every time the timezonemap jar version changes. Good luck!

**Comment by buti1021** [comment]
I think I have a kinda similar problem, I try to use the library in KNIME Java Snippet, I am unexperienced with Java and Maven and cant bring it to work. Got it to work in IntelliJ. When I try to run this code `        File mapDb = new File("C:\\Users\\username\\Desktop\\mapDb.bin");

        // Step 2: Use the extracted map database in initialization.
        try (InputStream input = new FileInputStream(mapDb)) {
            TimeZoneMap map = TimeZoneMap.forRegion(input, 34.4, -12.0, 71.00, 43.5);

            String out_get_timezone = map.getOverlappingTimeZone(48.169102, 10.283836).getZoneId();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
`
I get this error
```
java.lang.IllegalArgumentException: Location must be absolute: ..
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.checkValidLocation(AbstractRepositoryManager.java:749)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.contains(AbstractRepositoryManager.java:253)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.addRepository(AbstractRepositoryManager.java:166)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.notify(AbstractRepositoryManager.java:820)
	at org.eclipse.equinox.internal.p2.core.ProvisioningEventBus.dispatchEvent(ProvisioningEventBus.java:108)
	at org.eclipse.equinox.internal.p2.core.ProvisioningEventBus.dispatchEvent(ProvisioningEventBus.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

This seems pretty KNIME specific, when I try to run it with the jar but not the Maven Dependency I get this error:

`"C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\jbr\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\lib\idea_rt.jar=64045:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3\bin" -Dfile.encoding=UTF-8 -classpath C:\Users\TimBudras\IdeaProjects\untitled1\target\classes;C:\Users\TimBudras\.m2\repository\net\iakovlev\timeshape\2019b.8\timeshape-2019b.8.jar;C:\Users\TimBudras\.m2\repository\net\iakovlev\geojson-proto\1.1.0\geojson-proto-1.1.0.jar;C:\Users\TimBudras\.m2\repository\com\google\protobuf\protobuf-java\3.10.0\protobuf-java-3.10.0.jar;C:\Users\TimBudras\.m2\repository\com\esri\geometry\esri-geometry-api\2.2.1\esri-geometry-api-2.2.1.jar;C:\Users\TimBudras\.m2\repository\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;C:\Users\TimBudras\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.9.6\jackson-core-2.9.6.jar;C:\Users\TimBudras\.m2\repository\org\apache\commons\commons-compress\1.18\commons-compress-1.18.jar;C:\Users\TimBudras\.m2\repository\com\github\luben\zstd-jni\1.3.7-1\zstd-jni-1.3.7-1.jar;C:\Users\TimBudras\Desktop\timezonemap-4.0.jar Main
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at us.dustinj.timezonemap.TimeZoneMap$Companion.envelopeToPolygon(TimeZoneMap.kt)
	at us.dustinj.timezonemap.TimeZoneMap$Companion.forRegion(TimeZoneMap.kt:165)
	at us.dustinj.timezonemap.TimeZoneMap.forRegion(TimeZoneMap.kt)
	at Main.main(Main.java:12)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 4 more`

Is there anyway to get this running with the jar? Prefarably in KNIME? Thanks for your help!
